# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 11 ]
    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: :99
    steps:
    - uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    - name: Install Firefox
      uses: browser-actions/setup-firefox@latest
    - name: Start Xvfb
      if: matrix.os == 'ubuntu-latest'
      run: Xvfb $DISPLAY &
    - name: Run tests in chrome
      run: mvn -B test -Dbrowser=chrome
    - name: Upload target folder
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-reports-chrome
        path: |
          ${{ github.workspace }}/target/cucumber-reports
    - name: Run tests in firefox
      run: mvn -B test -Dbrowser=firefox
    - name: Upload target folder
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-reports-firefox
        path: |
          ${{ github.workspace }}/target/cucumber-reports
