# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    - name: Install Firefox
      uses: browser-actions/setup-firefox@latest
    - name: Execute tests in Chrome
      run: mvn clean test -Dbrowser=chrome
    - name: Upload target folder
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-reports-chrome
        path: |
          ${{ github.workspace }}/target/cucumber-reports
    - name: Execute tests in Firefox
      run: mvn clean test -Dbrowser=firefox
    - name: Upload target folder
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-reports-firefox
        path: |
          ${{ github.workspace }}/target/cucumber-reports
